apiVersion: v1
kind: Namespace
metadata:
  name: goapp-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: goapp-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: deepakramanan/goapp:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-registry-credentials
  strategy:
    type: Recreate

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: goapp-ns
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---

apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-credentials
  namespace: goapp-ns
type: kubernetes.io/dockerconfigjson
stringData:
  docker.username: deepakramanan
  docker.password: 9994522727
